import "./globals.css";

export const metadata = {
  title: "Food delivery app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="parent-page">
        {children}
      </body>
    </html>
  );
}
